version: "3.9"

services:
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./php/
    # `working_dir` - sets the working directory of the container that is created
    working_dir: /var/www
    volumes:
      - ../:/var/www
    container_name: "ca-php-su"

  nginx:
    image: nginx:1.23.1
    # `working_dir` - sets the working directory of the container that is created
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    container_name: "ca-nginx-su"
